project_id = "shapewebs"

[api]
enabled = true
port = 54321
schemas = ["public", "cms", "ops", "storage", "graphql_public"]
extra_search_path = ["public", "extensions", "cms", "ops"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.seed]
enabled = true
sql_paths = ["./seed/seed.sql"]

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "10MiB"

[auth]
enabled = true
site_url = "http://localhost:3001"
additional_redirect_urls = ["http://localhost:3001/**", "http://localhost:3000/**"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
enable_signup = false

[analytics]
enabled = false
