"use client";

import { useState, useTransition } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { adminAuthClient } from "@shapewebs/auth/client";
import { Buttons } from "@shapewebs/ui";
import { QRCodeSVG } from "qrcode.react";

import { getSafeAdminRedirectTarget } from "@/lib/redirect";

import styles from "./page.module.css";

type Enrollment = {
  totpUri: string;
};

type MfaScreenProps = {
  isConfigured: boolean;
  twoFactorEnabled: boolean;
};

function getEnrollmentSecret(totpUri: string): string {
  try {
    return new URL(totpUri).searchParams.get("secret") ?? "";
  } catch {
    return "";
  }
}

export function MfaScreen({ isConfigured, twoFactorEnabled }: MfaScreenProps) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [isPending, startTransition] = useTransition();
  const [code, setCode] = useState("");
  const [enrollment, setEnrollment] = useState<Enrollment | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const redirectTo = getSafeAdminRedirectTarget(
    searchParams.get("redirectTo") ?? "/dashboard",
  );
  const needsEnrollment = !twoFactorEnabled && enrollment === null;
  const enrollmentSecret = enrollment
    ? getEnrollmentSecret(enrollment.totpUri)
    : "";
  const stepUpReason = searchParams.get("reason");

  return (
    <div className={styles["sw-mfa-root-a5m1q7"]}>
      {!isConfigured ? (
        <p className={styles["sw-mfa-notice-b6n2r8"]}>
          Better Auth is not configured in this environment, so TOTP setup
          cannot be completed here.
        </p>
      ) : null}

      {stepUpReason === "password-link" ? (
        <p className={styles["sw-mfa-notice-b6n2r8"]}>
          Verify your authenticator code to request the password link. The email
          request will resume automatically afterward.
        </p>
      ) : stepUpReason === "step-up" ? (
        <p className={styles["sw-mfa-notice-b6n2r8"]}>
          This operation requires a recently verified authenticator code.
        </p>
      ) : null}

      {errorMessage ? (
        <p className={styles["sw-mfa-error-c7p3s9"]} role="alert">
          {errorMessage}
        </p>
      ) : null}

      {needsEnrollment && isConfigured ? (
        <Buttons.Button
          disabled={isPending}
          kind="primary"
          onClick={() => {
            startTransition(async () => {
              setErrorMessage(null);

              const { data, error } = await adminAuthClient.twoFactor.enable(
                {},
              );

              if (error || !data) {
                setErrorMessage(
                  "TOTP enrollment could not be started. Sign in again and retry.",
                );
                return;
              }

              setEnrollment({
                totpUri: data.totpURI,
              });
            });
          }}
          size="medium"
          type="button"
        >
          {isPending ? "Preparing setup..." : "Set up authenticator"}
        </Buttons.Button>
      ) : null}

      {enrollment ? (
        <>
          <div className={styles["sw-mfa-setup-d8q4t1"]}>
            <div className={styles["sw-mfa-qrpanel-e9r5v2"]}>
              <QRCodeSVG
                className={styles["sw-mfa-qrimage-f1s6w3"]}
                level="M"
                marginSize={4}
                size={220}
                title="Scan to add Shapewebs Admin to your authenticator"
                value={enrollment.totpUri}
              />
            </div>

            <div className={styles["sw-mfa-fields-g2t7x4"]}>
              <div>
                <h2>1. Add Shapewebs to your authenticator</h2>
                <p className={styles["sw-mfa-copy-h3v8y5"]}>
                  Scan the QR code in Google Authenticator or another TOTP app.
                  Signing in to the authenticator app does not add this account
                  automatically.
                </p>
              </div>

              <div>
                <p className={styles["sw-mfa-copy-h3v8y5"]}>
                  If you cannot scan, choose “Enter a setup key”, use account
                  name “Shapewebs Admin”, select a time-based key and enter this
                  one-time secret:
                </p>
                <div className={styles["sw-mfa-secret-j4w9z6"]}>
                  {enrollmentSecret}
                </div>
              </div>

              <div>
                <h2>2. Verify the changing code</h2>
                <p className={styles["sw-mfa-copy-h3v8y5"]}>
                  Enter the current six-digit Shapewebs code generated by the
                  authenticator below. The field text is not a usable code.
                </p>
              </div>
            </div>
          </div>

          <p className={styles["sw-mfa-notice-b6n2r8"]}>
            Recovery codes are intentionally unavailable until the
            administrative identity-recovery procedure has been implemented and
            tested. Keep the authenticator enrollment active.
          </p>
        </>
      ) : null}

      {!needsEnrollment && isConfigured ? (
        <div className={styles["sw-mfa-fields-g2t7x4"]}>
          <label className={styles["sw-mfa-field-k5x1a7"]}>
            <span>Authenticator code</span>
            <input
              autoComplete="one-time-code"
              inputMode="numeric"
              maxLength={6}
              onChange={(event) => {
                setCode(event.target.value.replace(/\D/g, "").slice(0, 6));
              }}
              pattern="[0-9]{6}"
              placeholder="Enter 6-digit code"
              type="text"
              value={code}
            />
          </label>

          <Buttons.Button
            disabled={!/^\d{6}$/.test(code) || isPending}
            kind="primary"
            onClick={() => {
              startTransition(async () => {
                setErrorMessage(null);

                const response = await fetch("/api/admin/step-up", {
                  body: JSON.stringify({ code }),
                  headers: {
                    "Content-Type": "application/json",
                  },
                  method: "POST",
                });

                if (!response.ok) {
                  setErrorMessage(
                    "The authenticator code was not accepted. Check the code and try again.",
                  );
                  return;
                }

                router.replace(redirectTo);
                router.refresh();
              });
            }}
            size="medium"
            type="button"
          >
            {isPending ? "Verifying..." : "Verify and continue"}
          </Buttons.Button>
        </div>
      ) : null}
    </div>
  );
}
