"use client";

import { useState, useTransition } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { adminAuthClient } from "@shapewebs/auth/client";
import { Buttons } from "@shapewebs/ui";
import { QRCodeSVG } from "qrcode.react";

import { getSafeAdminRedirectTarget } from "@/lib/redirect";

import styles from "./page.module.css";

type Enrollment = {
  totpUri: string;
};

type MfaScreenProps = {
  isConfigured: boolean;
  twoFactorEnabled: boolean;
};

function getEnrollmentSecret(totpUri: string): string {
  try {
    return new URL(totpUri).searchParams.get("secret") ?? "";
  } catch {
    return "";
  }
}

export function MfaScreen({ isConfigured, twoFactorEnabled }: MfaScreenProps) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [isPending, startTransition] = useTransition();
  const [code, setCode] = useState("");
  const [enrollment, setEnrollment] = useState<Enrollment | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const redirectTo = getSafeAdminRedirectTarget(
    searchParams.get("redirectTo") ?? "/dashboard",
  );
  const needsEnrollment = !twoFactorEnabled && enrollment === null;
  const enrollmentSecret = enrollment
    ? getEnrollmentSecret(enrollment.totpUri)
    : "";

  return (
    <div className={styles.stackM3q7d5}>
      <section className={styles.cardP8m2v4}>
        <div className={styles.copyBlockN7m3v1}>
          <p className={styles.eyebrowK1m9q4}>Security check</p>
          <h1 className={styles.titleQ2m8v6}>Authenticator verification</h1>
          <p className={styles.copyT6m4p2}>
            Shapewebs Admin requires a fresh six-digit TOTP code after Google or
            password sign-in and again before sensitive operations.
          </p>
        </div>

        {!isConfigured ? (
          <p className={styles.noticeStateW5m1d9}>
            Better Auth is not configured in this environment, so TOTP setup
            cannot be completed here.
          </p>
        ) : null}

        {searchParams.get("reason") === "step-up" ? (
          <p className={styles.noticeStateW5m1d9}>
            This operation requires a recently verified authenticator code.
          </p>
        ) : null}

        {errorMessage ? (
          <p className={styles.errorStateR7n2q1} role="alert">
            {errorMessage}
          </p>
        ) : null}

        {needsEnrollment && isConfigured ? (
          <Buttons.Button
            disabled={isPending}
            kind="primary"
            onClick={() => {
              startTransition(async () => {
                setErrorMessage(null);

                const { data, error } = await adminAuthClient.twoFactor.enable(
                  {},
                );

                if (error || !data) {
                  setErrorMessage(
                    "TOTP enrollment could not be started. Sign in again and retry.",
                  );
                  return;
                }

                setEnrollment({
                  totpUri: data.totpURI,
                });
              });
            }}
            size="medium"
            type="button"
          >
            {isPending ? "Preparing setup..." : "Set up authenticator"}
          </Buttons.Button>
        ) : null}

        {enrollment ? (
          <>
            <div className={styles.setupGridD3m8p2}>
              <div className={styles.qrPanelN6q5v7}>
                <QRCodeSVG
                  className={styles.qrImageK3p7m2}
                  level="M"
                  marginSize={4}
                  size={220}
                  title="Scan to add Shapewebs Admin to your authenticator"
                  value={enrollment.totpUri}
                />
              </div>

              <div className={styles.setupFieldsF4m6p1}>
                <div>
                  <h2>1. Add Shapewebs to your authenticator</h2>
                  <p className={styles.mutedH8p2q5}>
                    Scan the QR code in Google Authenticator or another TOTP
                    app. Signing in to the authenticator app does not add this
                    account automatically.
                  </p>
                </div>

                <div>
                  <p className={styles.mutedH8p2q5}>
                    If you cannot scan, choose “Enter a setup key”, use account
                    name “Shapewebs Admin”, select a time-based key and enter
                    this one-time secret:
                  </p>
                  <div className={styles.secretBoxJ7m2r8}>
                    {enrollmentSecret}
                  </div>
                </div>

                <div>
                  <h2>2. Verify the changing code</h2>
                  <p className={styles.mutedH8p2q5}>
                    Enter the current six-digit Shapewebs code generated by the
                    authenticator below. The field text is not a usable code.
                  </p>
                </div>
              </div>
            </div>

            <p className={styles.noticeStateW5m1d9}>
              Recovery codes are intentionally unavailable until the
              administrative identity-recovery procedure has been implemented
              and tested. Keep the authenticator enrollment active.
            </p>
          </>
        ) : null}

        {!needsEnrollment && isConfigured ? (
          <div className={styles.setupFieldsF4m6p1}>
            <label className={styles.fieldT5m3n9}>
              <span>Authenticator code</span>
              <input
                autoComplete="one-time-code"
                inputMode="numeric"
                maxLength={6}
                onChange={(event) => {
                  setCode(event.target.value.replace(/\D/g, "").slice(0, 6));
                }}
                pattern="[0-9]{6}"
                placeholder="Enter 6-digit code"
                type="text"
                value={code}
              />
            </label>

            <Buttons.Button
              disabled={!/^\d{6}$/.test(code) || isPending}
              kind="primary"
              onClick={() => {
                startTransition(async () => {
                  setErrorMessage(null);

                  const response = await fetch("/api/admin/step-up", {
                    body: JSON.stringify({ code }),
                    headers: {
                      "Content-Type": "application/json",
                    },
                    method: "POST",
                  });

                  if (!response.ok) {
                    setErrorMessage(
                      "The authenticator code was not accepted. Check the code and try again.",
                    );
                    return;
                  }

                  router.replace(redirectTo);
                  router.refresh();
                });
              }}
              size="medium"
              type="button"
            >
              {isPending ? "Verifying..." : "Verify and continue"}
            </Buttons.Button>
          </div>
        ) : null}
      </section>
    </div>
  );
}
