"use client";

import { useState, useTransition } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { adminAuthClient } from "@shapewebs/auth/client";
import { Authentication, Buttons, Forms } from "@shapewebs/ui";
import { QRCodeSVG } from "qrcode.react";

import { getSafeAdminRedirectTarget } from "@/lib/redirect";

import styles from "./page.module.css";

type Enrollment = {
  totpUri: string;
};

type MfaScreenProps = {
  isConfigured: boolean;
  twoFactorEnabled: boolean;
};

function getEnrollmentSecret(totpUri: string): string {
  try {
    return new URL(totpUri).searchParams.get("secret") ?? "";
  } catch {
    return "";
  }
}

export function MfaScreen({ isConfigured, twoFactorEnabled }: MfaScreenProps) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [isPending, startTransition] = useTransition();
  const [code, setCode] = useState("");
  const [enrollment, setEnrollment] = useState<Enrollment | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const redirectTo = getSafeAdminRedirectTarget(
    searchParams.get("redirectTo") ?? "/dashboard",
  );
  const needsEnrollment = !twoFactorEnabled && enrollment === null;
  const enrollmentSecret = enrollment
    ? getEnrollmentSecret(enrollment.totpUri)
    : "";
  const stepUpReason = searchParams.get("reason");

  return (
    <div className={styles["mfa-root-xs1ivr"]}>
      {!isConfigured ? (
        <Authentication.AuthMessage tone="error">
          Better Auth is not configured in this environment, so TOTP setup
          cannot be completed here.
        </Authentication.AuthMessage>
      ) : null}

      {stepUpReason === "password-link" ? (
        <Authentication.AuthMessage>
          Verify your authenticator code to request the password link. The email
          request will resume automatically afterward.
        </Authentication.AuthMessage>
      ) : stepUpReason === "step-up" ? (
        <Authentication.AuthMessage>
          This operation requires a recently verified authenticator code.
        </Authentication.AuthMessage>
      ) : null}

      {errorMessage ? (
        <Authentication.AuthMessage tone="error">
          {errorMessage}
        </Authentication.AuthMessage>
      ) : null}

      {needsEnrollment && isConfigured ? (
        <Buttons.Button
          kind="brand"
          onClick={() => {
            startTransition(async () => {
              setErrorMessage(null);

              try {
                const { data, error } = await adminAuthClient.twoFactor.enable(
                  {},
                );

                if (error || !data) {
                  setErrorMessage(
                    "TOTP enrollment could not be started. Sign in again and retry.",
                  );
                  return;
                }

                setEnrollment({
                  totpUri: data.totpURI,
                });
              } catch {
                setErrorMessage(
                  "Authenticator setup is temporarily unavailable. Please try again.",
                );
              }
            });
          }}
          pending={isPending}
          pendingLabel="Preparing authenticator setup"
          size="large"
          type="button"
        >
          Set up authenticator
        </Buttons.Button>
      ) : null}

      {enrollment ? (
        <>
          <div className={styles["mfa-setup-gd76s4"]}>
            <div className={styles["mfa-qrpanel-by4yak"]}>
              <QRCodeSVG
                className={styles["mfa-qrimage-dlu8d5"]}
                level="M"
                marginSize={4}
                size={220}
                title="Scan to add Shapewebs Admin to your authenticator"
                value={enrollment.totpUri}
              />
            </div>

            <div className={styles["mfa-fields-k0o163"]}>
              <div>
                <h2>1. Add Shapewebs to your authenticator</h2>
                <p className={styles["mfa-copy-d3vyng"]}>
                  Scan the QR code in Google Authenticator or another TOTP app.
                  Signing in to the authenticator app does not add this account
                  automatically.
                </p>
              </div>

              <div>
                <p className={styles["mfa-copy-d3vyng"]}>
                  If you cannot scan, choose “Enter a setup key”, use account
                  name “Shapewebs Admin”, select a time-based key and enter this
                  one-time secret:
                </p>
                <div className={styles["mfa-secret-f9v6z5"]}>
                  {enrollmentSecret}
                </div>
              </div>

              <div>
                <h2>2. Verify the changing code</h2>
                <p className={styles["mfa-copy-d3vyng"]}>
                  Enter the current six-digit Shapewebs code generated by the
                  authenticator below. The field text is not a usable code.
                </p>
              </div>
            </div>
          </div>

          <Authentication.AuthMessage>
            Recovery codes are intentionally unavailable until the
            administrative identity-recovery procedure has been implemented and
            tested. Keep the authenticator enrollment active.
          </Authentication.AuthMessage>
        </>
      ) : null}

      {!needsEnrollment && isConfigured ? (
        <div className={styles["mfa-fields-k0o163"]}>
          <Forms.Field>
            <Forms.Label htmlFor="employee-totp-code">
              Authenticator code
            </Forms.Label>
            <Forms.InputOtp
              autoComplete="one-time-code"
              disabled={isPending}
              id="employee-totp-code"
              inputMode="numeric"
              maxLength={6}
              onChange={(event) => {
                setCode(event.target.value.replace(/\D/g, "").slice(0, 6));
              }}
              pattern="[0-9]{6}"
              placeholder="Enter 6-digit code"
              type="text"
              value={code}
            />
          </Forms.Field>

          <Buttons.Button
            disabled={!/^\d{6}$/.test(code)}
            kind="brand"
            onClick={() => {
              startTransition(async () => {
                setErrorMessage(null);

                try {
                  const response = await fetch("/api/admin/step-up", {
                    body: JSON.stringify({ code }),
                    headers: {
                      "Content-Type": "application/json",
                    },
                    method: "POST",
                  });

                  if (!response.ok) {
                    setErrorMessage(
                      "The authenticator code was not accepted. Check the code and try again.",
                    );
                    return;
                  }

                  router.replace(redirectTo);
                  router.refresh();
                } catch {
                  setErrorMessage(
                    "Authenticator verification is temporarily unavailable. Please try again.",
                  );
                }
              });
            }}
            pending={isPending}
            pendingLabel="Verifying authenticator code"
            size="large"
            type="button"
          >
            Verify and continue
          </Buttons.Button>
        </div>
      ) : null}
    </div>
  );
}
