export const componentRegistry = {
  brand: {
    ShapewebsBrand: "styled",
  },
  buttons: {
    Button: "styled",
    ButtonAnchor: "styled",
    ButtonLink: "styled",
    ButtonGroup: "styled",
    CloseButton: "styled",
    ToggleButton: "styled",
    ToggleButtonGroup: "styled",
  },
  collections: {
    Dropdown: "scaffolded",
    ListBox: "scaffolded",
    TagGroup: "scaffolded",
  },
  colors: {
    ColorArea: "scaffolded",
    ColorField: "scaffolded",
    ColorPicker: "scaffolded",
    ColorSlider: "scaffolded",
    ColorSwatch: "scaffolded",
    ColorSwatchPicker: "scaffolded",
  },
  controls: {
    Slider: "scaffolded",
    Switch: "scaffolded",
  },
  dataDisplay: {
    Badge: "scaffolded",
    Chip: "scaffolded",
    Table: "scaffolded",
  },
  dateAndTime: {
    Calendar: "scaffolded",
    DateField: "scaffolded",
    DatePicker: "scaffolded",
    DateRangePicker: "scaffolded",
    RangeCalendar: "scaffolded",
    TimeField: "scaffolded",
  },
  feedback: {
    Alert: "scaffolded",
    Meter: "scaffolded",
    ProgressBar: "scaffolded",
    ProgressCircle: "scaffolded",
    Skeleton: "scaffolded",
    Spinner: "styled",
  },
  forms: {
    Checkbox: "scaffolded",
    CheckboxGroup: "scaffolded",
    Description: "scaffolded",
    ErrorMessage: "scaffolded",
    FieldError: "scaffolded",
    FieldSet: "scaffolded",
    Form: "scaffolded",
    Input: "scaffolded",
    InputGroup: "scaffolded",
    InputOtp: "scaffolded",
    Label: "scaffolded",
    NumberField: "scaffolded",
    RadioGroup: "scaffolded",
    SearchField: "scaffolded",
    TextField: "scaffolded",
    TextArea: "scaffolded",
  },
  layout: {
    Card: "styled",
    Cluster: "styled",
    Container: "styled",
    Separator: "scaffolded",
    Stack: "styled",
    Surface: "styled",
    Toolbar: "scaffolded",
  },
  media: {
    Avatar: "scaffolded",
  },
  navigation: {
    Accordion: "scaffolded",
    Breadcrumbs: "scaffolded",
    Disclosure: "scaffolded",
    DisclosureGroup: "scaffolded",
    Link: "styled",
    Pagination: "scaffolded",
    Tabs: "scaffolded",
  },
  overlays: {
    Alert: "scaffolded",
    Dialog: "scaffolded",
    Drawer: "scaffolded",
    Modal: "scaffolded",
    Popover: "scaffolded",
    Toast: "scaffolded",
    Tooltip: "scaffolded",
  },
  pickers: {
    Autocomplete: "scaffolded",
    ComboBox: "scaffolded",
    Select: "scaffolded",
  },
  typography: {
    Kbd: "scaffolded",
  },
  utilities: {
    ScrollShadow: "scaffolded",
  },
} as const;
